--CREATE TABLE Unidades_Federacao(
--	ID_Unidades_Federacao INT IDENTITY (1, 1) NOT NULL,
--	Descricao_Unidades_Federacao VARCHAR (100) NULL ,
--	Sigla_UF CHAR(2) NULL ,
--	Regiao_Brasil VARCHAR (20),
--	Situacao BIT NULL DEFAULT 1,
--	DataInclusao DATETIME NULL DEFAULT GETDATE(),
--	DataAlteracao DATETIME NULL,
--	DataExclusao DATETIME NULL
--    CONSTRAINT PK_Unidade_Federacao PRIMARY KEY (ID_Unidades_Federacao)
--)
--GO
