SET IDENTITY_INSERT Tipo_Logradouro ON

INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (1, 'Avenida')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (2, 'Aeroporto')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (3, 'Alameda')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (4, 'Área')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (5, 'Campo')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (6, 'Chácara')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (7, 'Colônia')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (8, 'Condomínio')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (9, 'Conjunto')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (10, 'Distrito')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (11, 'Esplanada')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (12, 'Estação')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (13, 'Estrada')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (14, 'Favela ')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (15, 'Fazenda')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (16, 'Feira')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (17, 'Jardim')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (18, 'Ladeira')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (19, 'Lago')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (20, 'Lagoa')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (21, 'Largo')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (22, 'Loteamento')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (23, 'Morro')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (24, 'Núcleo')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (25, 'Parque')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (26, 'Passarela')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (27, 'Pátio')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (28, 'Praça')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (29, 'Quadra')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (30, 'Recanto')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (31, 'Residencial')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (32, 'Rodovia')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (33, 'Setor')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (34, 'Sítio')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (35, 'Travessa')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (36, 'Trecho')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (37, 'Trevo')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (38, 'Vale')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (39, 'Vereda')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (40, 'Via')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (41, 'Viaduto')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (42, 'Viela')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (43, 'Vila')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (44, 'Outros')
INSERT INTO Tipo_Logradouro (ID_Tipo_Logradouro, Tipo_Logradouro) VALUES (45, 'Rua')

SET IDENTITY_INSERT Tipo_Logradouro OFF