
INSERT INTO Area_Conhecimento(Descricao_Area_Conhecimento) VALUES
('TécnicasPlanejamentoUrbanosRegionais'),
('Serviços Urbanos e Regionais'),
('Administração Municipal e Urbana'),
('Estudos da Habitação'),
('Aspectos Sociais do Planejamento Urbano e Regional'),
('Aspectos Econômicos do Planejamento Urbano e Regional'),
('Aspectos Físico-Ambientais do Planejamento Urbano e Regional'),
('Serviços Comunitários'),
('Infra-Estruturas Urbanas e Regionais'),
('Transporte e Tráfego Urbano e Regional'),
('Legislação Urbana e Regional'),
('Demografia'),
('Distribuição Espacial'),
('Distribuição Espacial Geral'),
('Distribuição Espacial Urbana'),
('Distribuição Espacial Rural'),
('Tendência Populacional'),
('Tendências Passadas'),
('Taxas e Estimativas Correntes'),
('Projeções'),
('Componentes da Dinâmica Demográfica'),
('Fecundidade'),
('Mortalidade'),
('Migração'),
('Nupcialidade e Família'),
('Casamento e Divórcio'),
('Família e Reprodução'),
('Demografia Histórica'),
('Distribuição Espacial'),
('NatalidadeMortalidadeMigração'),
('Nupcialidade e Família'),
('Métodos e Técnicas de Demografia Histórica'),
('Política Pública e População'),
('Política Populacional'),
('Políticas de Redistribuição de População'),
('Políticas de Planejamento Familiar'),
('Fontes de Dados Demográficos'),
('Ciência da Informação'),
('Teoria da Informação'),
('Teoria Geral da Informação'),
('Processos da Comunicação'),
('Representação da Informação'),
('Biblioteconomia'),
('Teoria da Classificação'),
('Métodos Quantitativos. Bibliometria'),
('Técnicas de Recuperação de Informação'),
('Processos de Disseminação da Informação'),
('Arquivologia'),
('Organização de Arquivos'),
('Museologia'),
('Comunicação'),
('Teoria da Comunicação'),
('Jornalismo e Editoração'),
('Teoria e Ética do Jornalismo'),
('Organização Editorial de Jornais'),
('Organização Comercial de Jornais'),
('Jornalismo Especializado
(ComunitárioRuralEmpresarialCientífico),'),
('Rádio e Televisão'),
('Radiodifusão'),
('Videodifusão'),
('Relações Públicas e Propaganda'),
('Comunicação Visual'),
('Serviço Social'),
('Fundamentos do Serviço Social'),
('Serviço Social Aplicado'),
('Serviço Social do Trabalho'),
('Serviço Social da Educação'),
('Serviço Social do Menor'),
('Serviço Social da Saúde'),
('Serviço Social da Habitação'),
('Economia Doméstica'),
('Desenho Industrial'),
('Programação Visual'),
('Desenho de Produto'),
('Turismo'),
('Ciências Humanas'),
('Filosofia'),
('História da Filosofia'),
('Metafísica'),
('Lógica'),
('Ética'),
('Epistemologia'),
('Filosofia Brasileira'),
('Sociologia'),
('Fundamentos da Sociologia'),
('Teoria Sociológica'),
('História da Sociologia'),
('Sociologia do Conhecimento'),
('Sociologia do Desenvolvimento'),
('Sociologia Urbana'),
('Sociologia Rural'),
('Sociologia da Saúde'),
('Outras Sociologias Específicas'),
('Antropologia'),
('Teoria Antropológica'),
('Etnologia Indígena'),
('Antropologia Urbana'),
('Antropologia Rural'),
('Antropologia das Populações Afro-Brasileiras'),
('Arqueologia'),
('Teoria e Método em Arqueologia'),
('Arqueologia Pré-Histórica'),
('Arqueologia Histórica'),
('História'),
('Teoria e Filosofia da História'),
('História Antiga e Medieval'),
('História Moderna e Contemporânea'),
('História da América'),
('História dos Estados Unidos'),
('História Latino-Americana'),
('História do Brasil'),
('História do Brasil Colônia'),
('História do Brasil Império'),
('História do Brasil República'),
('História Regional do Brasil'),
('História das Ciências'),
('Geografia'),
('Geografia Humana'),
('Geografia da População'),
('Geografia Agrária'),
('Geografia Urbana'),
('Geografia Econômica'),
('Geografia Política'),
('Geografia Regional'),
('Teoria do Desenvolvimento Regional'),
('Regionalização'),
('Análise Regional'),
('Psicologia'),
('Fundamentos e Medidas da Psicologia'),
('HistóriaTeorias e Sistemas em Psicologia'),
('MetodologiaInstrumentação e Equipamento em Psicologia'),
('Construção e Validade de TestesEscalas e Outras Medidas Psicológicas'),
('Técnicas de Processamento EstatísticoMatemático e Computacional em Psicologia'),
('Psicologia Experimental'),
('Processos Perceptuais e Motores'),
('Processos de AprendizagemMemória e Motivação'),
('Processos Cognitivos e Atencionais'),
('Estados Subjetivos e Emoção'),
('Psicologia Fisiológica'),
('NeurologiaEletrofisiologia e Comportamento'),
('Processos Psico-Fisiológicos'),
('Estimulação Elétrica e com Drogas; Comportamento'),
('Psicobiologia'),
('Psicologia Comparativa'),
('Estudos Naturalísticos do Comportamento Animal'),
('Mecanismos Instintivos e Processos Sociais em Animais'),
('Psicologia Social'),
('Relações Interpessoais'),
('Processos Grupais e de Comunicação'),
('Papéis e Estruturas Sociais; Indivíduo'),
('Psicologia Cognitiva'),
('Psicologia do Desenvolvimento Humano'),
('Processos Perceptuais e Cognitivos; Desenvolvimento'),
('Desenvolvimento Social e da Personalidade'),
('Psicologia do Ensino e da Aprendizagem'),
('Planejamento Institucional'),
('Programação de Condições de Ensino'),
('Treinamento de Pessoal'),
('Aprendizagem e Desempenho Acadêmicos'),
('Ensino e Aprendizagem na Sala de Aula'),
('Psicologia do Trabalho e Organizacional'),
('Análise Institucional'),
('Recrutamento e Seleção de Pessoal'),
('Treinamento e Avaliação'),
('Fatores Humanos no Trabalho'),
('Planejamento Ambiental e Comportamento Humano'),
('Tratamento e Prevenção Psicológica'),
('Intervenção Terapêutica'),
('Programas de Atendimento Comunitário'),
('Treinamento e Reabilitação'),
('Desvios da Conduta'),
('Distúrbios da Linguagem'),
('Distúrbios Psicossomáticos'),
('Educação'),
('Fundamentos da Educação'),
('Filosofia da Educação'),
('História da Educação'),
('Sociologia da Educação'),
('Antropologia Educacional'),
('Economia da Educação'),
('Psicologia Educacional'),
('Administração Educacional'),
('Administração de Sistemas Educacionais'),
('Administração de Unidades Educativas'),
('Planejamento e Avaliação Educacional'),
('Política Educacional'),
('Planejamento Educacional'),
('Avaliação de SistemasInstituiçõesPlanos e Programas Educacionais'),
('Ensino-Aprendizagem'),
('Teorias da Instrução'),
('Métodos e Técnicas de Ensino'),
('Tecnologia Educacional'),
('Avaliação da Aprendizagem'),
('Currículo'),
('Teoria Geral de Planejamento e Desenvolvimento Curricular'),
('Currículos Específicos para Níveis e Tipos de Educação'),
('Orientação e Aconselhamento'),
('Orientação Educacional'),
('Orientação Vocacional'),
('Tópicos Específicos de Educação'),
('Educação de Adultos'),
('Educação Permanente'),
('Educação Rural'),
('Educação em Periferias Urbanas'),
('Educação Especial'),
('Educação Pré-Escolar'),
('Ensino Profissionalizante'),
('Ciência Política'),
('Teoria Política'),
('Teoria Política Clássica'),
('Teoria Política Medieval'),
('Teoria Política Moderna'),
('Teoria Política Contemporânea'),
('Estado e Governo'),
('Estrutura e Transformação do Estado'),
('Sistemas Governamentais Comparados'),
('Relações Intergovernamentais'),
('Estudos do Poder Local'),
('Instituições Governamentais Específicas'),
('Comportamento Político'),
('Estudos Eleitorais e Partidos Políticos'),
('Atitude e Ideologias Políticas'),
('Conflitos e Coalizões Políticas'),
('Comportamento Legislativo'),
('Classes Sociais e Grupos de Interesse'),
('Políticas Públicas'),
('Análise do Processo Decisório'),
('Análise Institucional'),
('Técnicas de Antecipação'),
('Política Internacional'),
('Política Externa do Brasil'),
('Organizações Internacionais'),
('Integração InternacionalConflitoGuerra e Paz'),
('Relações InternacionaisBilaterais e Multilaterais'),
('Teologia'),
('História da Teologia'),
('Teologia Moral'),
('Teologia Sistemática'),
('Teologia Pastoral'),
('LingüísticaLetras e Artes'),
('Lingüística'),
('Teoria e Análise Lingüística'),
('Filosofia da Linguagem'),
('Lingüística Histórica'),
('Sociolingüística e Dialetologia'),
('Psicolingüística'),
('Lingüística Aplicada'),
('Letras'),
('Língua Portuguesa'),
('Línguas Estrangeiras Modernas'),
('Línguas Clássicas'),
('Línguas Indígenas'),
('Teoria Literária'),
('Literatura Brasileira'),
('Outras Literaturas Vernáculas'),
('Literaturas Estrangeiras Modernas'),
('Literaturas Clássicas'),
('Literatura Comparada'),
('Artes'),
('Fundamentos e Crítica das Artes'),
('Teoria da Arte'),
('História da Arte'),
('Crítica da Arte'),
('Artes Plásticas'),
('Pintura'),
('Desenho'),
('Gravura'),
('Escultura'),
('Cerâmica'),
('Tecelagem'),
('Música'),
('Regência'),
('Instrumentação Musical'),
('Composição Musical'),
('Canto'),
('Dança'),
('Execução da Dança'),
('Coreografia'),
('Teatro'),
('Dramaturgia'),
('Direção Teatral'),
('Cenografia'),
('Interpretação Teatral'),
('Ópera'),
('Fotografia'),
('Cinema'),
('Administração e Produção de Filmes'),
('Roteiro e Direção Cinematográficos'),
('Técnicas de Registro e Processamento de Filmes'),
('Interpretação Cinematográfica'),
('Artes do Vídeo'),
('Educação Artística'),
('Outros'),
('Administração Hospitalar'),
('Administração Rural'),
('Carreira Militar'),
('Carreira Religiosa'),
('Ciências'),
('Biomedicina'),
('Ciências Atuarias'),
('Ciências Sociais'),
('Decoração'),
('Desenho de Moda'),
('Desenho de Projetos'),
('Diplomacia'),
('Engenharia de Agrimensura'),
('Engenharia Cartografica'),
('Engenharia de Armamentos'),
('Engenharia Mecatrônica'),
('Engenharia Textil'),
('Estudos Sociais'),
('Historia Natural'),
('Química Industrial'),
('Relações Internacionais'),
('Relações Públicas'),
('Secretariado Executivo'),
('Multidisciplinar')
GO
